### ISSUE TITLE
Je cherche un développeur passionné

### ISSUE THREAD

**Issue by adauleu** [arthurkirsz/zephos#1]

**Comment by arthurkirsz** [comment]
Bonjour Alban,

Tu ne pensais peut être pas à mal (je l'espère en tout cas), mais j'apprécie très peu l'originalité de ton approche. 

Ce n'est pas cool de mettre un message qui fait l'éloge de Xebia dans mon repo, je considère cela comme un spam (Sans compter le joli lien vers ton profil Linkedin).

Bref, retire moi ça s'il te plait.

Au plaisir de te lire ailleurs que sur mes repos github

**Comment by adauleu** [comment]
Bonjour Arthur
Je ne pensais bien sûr pas à mal.
Désolé que cette approche t'ai dérangée. J'ai retiré mon message

Alban
